export const BLOG_POSTS = [
  {
    "title": "You Are Not Alone in This",
    "slug": "you-not-alone-in-this",
    "excerpt": "I started this page because I was tired of watching people suffer in silence. Mental health is real. Pain is real. And you deserve a space where that is finally said out loud.",
    "content": "<p>I want to start with something simple.</p><p>You are not alone.</p><p>I know that sounds like something people write on greeting cards and forget by morning. But I mean it. I mean it in the way that only someone who has sat across from real, breathing, hurting human beings can mean it.</p><p>I started Pain2Purpose because I was tired. Tired of watching people carry weight that was never meant to be carried alone. Tired of the silence. Tired of the stigma that tells us that struggling means weakness.</p><h2>Why I Started Writing</h2><p>Mental health conversations in our communities — particularly in Nigeria — are often buried. People say, <em>\"Just pray about it.\"</em> Or <em>\"Others have it worse.\"</em> Or they look at you like something is wrong with you for daring to name what you feel.</p><p>I want this space to be different.</p><p>I want this to be the place where you come when you don't have words for what you're carrying. Where you find someone who says: <em>I see you. It is okay to not be okay. And there is help.</em></p><h2>What This Space Is For</h2><p>Here, we will talk about grief. We will talk about relationships. We will talk about the quiet depression that smiles at people on Sundays and weeps alone on Monday mornings. We will talk about children who are different, and parents who don't know how to cope. We will talk about all of it.</p><p>Because silence has never healed anyone.</p><p>If you're reading this and something in your chest just exhaled — welcome. This space is for you.</p><blockquote><p><em>\"The bravest thing you can do is admit you need help — and then go get it.\"</em></p></blockquote>",
    "coverImage": "",
    "coverImageAlt": "A warm candle flame in a dark room",
    "categorySlug": "sandras-journal",
    "pillar": null,
    "topics": ["mental health awareness"],
    "tags": ["mental health", "counselling", "welcome", "healing", "community", "Nigeria"],
    "type": "micro",
    "status": "published",
    "source": "human",
    "scheduledFor": null,
    "publishedAt": 1630742400000,
    "readingTime": 3,
    "actualReadingTime": null,
    "metaTitle": "You Are Not Alone in This | Pain2Purpose",
    "metaDescription": "Sandra Opara launches Pain2Purpose — a safe space to talk openly about mental health, healing, and the courage it takes to ask for help.",
    "focusKeyword": "mental health support Nigeria",
    "isFeatured": false,
    "isArchived": false
  },
  {
    "title": "What Is Depression, Really?",
    "slug": "what-is-depression-really",
    "excerpt": "Depression is not sadness. It is something heavier, quieter, and far more misunderstood — especially in African homes where we are told to just be grateful.",
    "content": "<p>Let me tell you something they don't say enough.</p><p>Depression is not just sadness.</p><p>It is waking up and wondering why you should bother. It is exhaustion that sleep does not fix. It is smiling at your neighbour, laughing at your cousin's joke, showing up to work — and feeling absolutely nothing inside.</p><p>It is, sometimes, the person who seems fine.</p><h2>The African Version We Don't Talk About</h2><p>In many Nigerian homes, the conversation goes like this: <em>\"Depression ke? What do you have to be depressed about? Do you know what your grandmother suffered?\"</em></p><p>And just like that, the door is shut.</p><p>But suffering is not a competition. Your pain is not disqualified because someone else has a bigger story. Depression does not check your bank account, your church attendance, or your family's reputation before it arrives.</p><h2>Signs That Deserve Attention</h2><p>You might be struggling with depression if you notice persistent sadness or emotional numbness that lasts more than two weeks. Losing interest in things that once brought you joy is another quiet sign. Sleeping too much or not at all, changes in appetite, difficulty concentrating, and withdrawing from people who care about you — these all matter.</p><p>And sometimes, depression shows up as irritability or anger — not just tears. Especially in men.</p><h2>It Is Not Weakness. It Is Not Sin.</h2><p>I have heard people say that depression is a spiritual problem. Maybe for some, there is a spiritual dimension. But it is also a medical one. The brain is an organ. And organs, like any part of the body, can struggle.</p><p>If your leg was broken, you would not tell yourself to just have faith and walk it off. Please extend the same logic to your mind.</p><p>There is help available. <a href='/services/individual-counselling'>Counselling works.</a> You don't have to carry this alone.</p>",
    "coverImage": "",
    "coverImageAlt": "A person sitting alone in a dimly lit room",
    "categorySlug": "mental-wellness",
    "pillar": null,
    "topics": ["depression awareness"],
    "tags": ["depression", "mental health", "Nigeria", "stigma", "counselling", "healing"],
    "type": "cluster",
    "status": "published",
    "source": "human",
    "scheduledFor": null,
    "publishedAt": 1633939200000,
    "readingTime": 4,
    "actualReadingTime": null,
    "metaTitle": "What Is Depression, Really? | Pain2Purpose",
    "metaDescription": "Depression is more than sadness. Sandra Opara explains what depression truly looks and feels like — and why African communities need to start this conversation.",
    "focusKeyword": "what is depression Nigeria",
    "isFeatured": false,
    "isArchived": false
  },
  {
    "title": "Dear Grieving Mother",
    "slug": "dear-grieving-mother",
    "excerpt": "You held them for nine months. You named them. You dreamed for them. And now they are gone. This letter is for you.",
    "content": "<p>Dear Grieving Mother,</p><p>I see you.</p><p>Not the version of you that is holding it together for the sake of the other children, or for your husband, or for the church people who come to sit with you and don't know what to say.</p><p>I see the version of you that cries in the bathroom. The one who walks into their room and just stands there.</p><h2>Your Grief Is Sacred</h2><p>The loss of a child — at any age, in any way — is a grief unlike any other. It is not natural. It is not supposed to happen this way. And no one — not time, not scripture, not the well-meaning aunties — gets to tell you how long it is supposed to hurt.</p><p>It will hurt for as long as it hurts. And that is allowed.</p><h2>What You Don't Have to Do</h2><p>You don't have to be strong right now. Strength is not the same as healing. You don't have to smile for visitors. You don't have to explain why you're still struggling months later. And you absolutely do not have to move on.</p><p>You move <em>forward</em>. Not on.</p><h2>You Are Still a Mother</h2><p>Nobody's death can un-mother you. You are still their mother. You will always be their mother. And the love you carry for them — that is not grief. That is legacy.</p><p>Please reach out if you need a safe space to process this. <a href='/services/grief-and-loss-support'>Our grief support sessions</a> are here — not to rush your healing, but to walk it with you.</p><p>You are not alone.</p><p>With love,<br/>Sandra</p>",
    "coverImage": "",
    "coverImageAlt": "A mother's hands holding a small shoe",
    "categorySlug": "grief-and-loss",
    "pillar": null,
    "topics": ["child loss", "maternal grief"],
    "tags": ["grief", "loss", "motherhood", "child loss", "healing", "mental health support"],
    "type": "insight",
    "status": "published",
    "source": "human",
    "scheduledFor": null,
    "publishedAt": 1637395200000,
    "readingTime": 4,
    "actualReadingTime": null,
    "metaTitle": "Dear Grieving Mother | Pain2Purpose",
    "metaDescription": "A heartfelt letter to mothers who have lost a child. Sandra Opara speaks directly to the grief that no one should have to carry alone.",
    "focusKeyword": "grief after losing a child",
    "isFeatured": false,
    "isArchived": false
  },
  {
    "title": "When Your Marriage Feels Like a Prison",
    "slug": "when-your-marriage-feels-like-a-prison",
    "excerpt": "She had a wedding that trended. Beautiful photos. People said she glowed. Three years later, she sits in my office and says, 'I feel so alone inside this marriage.' You are not the only one.",
    "content": "<p>She had a wedding that trended on Instagram. Stunning photos. People said she glowed.</p><p>Three years later, she sat in my office and said quietly, <em>\"I feel more alone now than I ever did when I was single.\"</em></p><p>I hear this more often than people would expect.</p><h2>The Marriage Nobody Talks About</h2><p>There is a kind of marriage that looks fine from the outside — prayers at Sunday service, family functions attended together, children who seem happy. But inside the walls of that home, there is distance. Silence that has weight. Two people performing a partnership.</p><p>If this is your story, I want you to know: you are not crazy. You are not failing. And you are far from alone.</p><h2>Why People Stay Silent</h2><p>In Nigerian society especially, admitting your marriage is struggling can feel like public shame. You think of your parents, your pastor, the money spent on the wedding. You think, <em>\"People will say I couldn't manage my home.\"</em></p><p>And so you stay silent. And the isolation grows.</p><h2>What Needs to Be Said</h2><p>Staying in a difficult marriage does not automatically make you strong. And leaving does not automatically make you a failure. What matters is that you are honest — with yourself first.</p><p>Ask: Am I safe here? Am I seen? Is there willingness from both of us to do the work? Or has this become a performance of a marriage that no longer exists?</p><h2>There Is Help</h2><p>Couples counselling is not a last resort. It is not a sign you have failed. It is a sign you are serious enough about this relationship to fight for it — or clear-eyed enough to face what it truly is.</p><p>If you are in this place, <a href='/services/couples-counselling'>couples counselling</a> can help both of you find your footing — or your way forward. Either way, you deserve honesty and peace.</p>",
    "coverImage": "",
    "coverImageAlt": "Two people sitting apart on a bed, not looking at each other",
    "categorySlug": "healing-and-recovery",
    "pillar": null,
    "topics": ["marriage struggles"],
    "tags": ["marriage", "relationships", "loneliness", "couples counselling", "mental health", "Nigeria"],
    "type": "insight",
    "status": "published",
    "source": "human",
    "scheduledFor": null,
    "publishedAt": 1642233600000,
    "readingTime": 5,
    "actualReadingTime": null,
    "metaTitle": "When Your Marriage Feels Like a Prison | Pain2Purpose",
    "metaDescription": "Loneliness inside a marriage is real — and it's more common than you think. Sandra Opara opens a conversation about the marriages nobody talks about.",
    "focusKeyword": "marriage struggles counselling Nigeria",
    "isFeatured": false,
    "isArchived": false
  },
  {
    "title": "My Son Is on the Spectrum — And I Almost Missed It",
    "slug": "my-son-is-on-the-spectrum-almost-missed-it",
    "excerpt": "When my nephew was three, he didn't point at things. He didn't wave goodbye. He lined up his toy cars in perfect rows and screamed if one was moved. Nobody told us what that meant.",
    "content": "<p>When a close family friend's son, Emeka, was three years old, he didn't point at things he wanted. He didn't wave goodbye.</p><p>He lined up his toy cars in perfect, precise rows — and if anyone moved even one, he would scream for twenty minutes.</p><p>The family prayed. The grandmother said he was a serious child. The neighbours suggested he was just stubborn.</p><p>Nobody told them the word: autism.</p><h2>The Diagnosis Nobody Prepares You For</h2><p>I have walked with many families through this journey — the initial confusion, the long road to diagnosis, and then the diagnosis itself, which arrives like a door swinging open into a room you didn't know existed.</p><p>Some parents grieve. Some feel relief — finally, a name for it. Most feel both, often in the same afternoon.</p><h2>What Autism Is Not</h2><p>Autism is not a punishment. It is not caused by vaccines, despite what the internet says. It is not the result of a mother's sin or a spiritual attack. It is not a disease to be cured.</p><p>It is a different way of experiencing the world. Slower to speak sometimes, but often faster to feel. Particular in ways that society calls difficult — but which, understood and supported, become gifts.</p><h2>What Nigerian Families Need to Know</h2><p>Early intervention matters enormously. The earlier a child on the spectrum receives the right support — speech therapy, occupational therapy, structured learning environments — the better their development outcomes.</p><p>But first, someone has to notice. Someone has to say the word. Someone has to stop attributing every difference to spiritual warfare and begin asking: what does my child actually need?</p><p>If you suspect your child may be on the autism spectrum, or if you have recently received a diagnosis and don't know where to start, <a href='/services/autism-family-support'>our autism family support sessions</a> are here to help you navigate this journey — with compassion, not judgment.</p>",
    "coverImage": "",
    "coverImageAlt": "A child playing alone with toy cars, lined up in a row",
    "categorySlug": "autism-and-family",
    "pillar": null,
    "topics": ["autism diagnosis", "parenting"],
    "tags": ["autism", "spectrum", "parenting", "early intervention", "Nigeria", "family support", "child development"],
    "type": "pillar",
    "status": "published",
    "source": "human",
    "scheduledFor": null,
    "publishedAt": 1646726400000,
    "readingTime": 6,
    "actualReadingTime": null,
    "metaTitle": "My Son Is on the Spectrum — And I Almost Missed It | Pain2Purpose",
    "metaDescription": "Sandra Opara shares how families in Nigeria miss early autism signs — and what parents need to know about early intervention and support.",
    "focusKeyword": "autism diagnosis Nigeria parenting",
    "isFeatured": false,
    "isArchived": false
  },
  {
    "title": "Anxiety Is Not Just Worrying Too Much",
    "slug": "anxiety-is-not-just-worrying-too-much",
    "excerpt": "Ngozi told me she couldn't breathe at her own wedding. Not from emotion — from panic. She had been anxious her whole life and thought everyone felt that way.",
    "content": "<p>Ngozi told me she couldn't breathe at her own wedding.</p><p>Not from emotion. Not from joy. From panic.</p><p>Her heart was pounding. Her hands were trembling. She kept thinking, <em>\"Something terrible is about to happen,\"</em> even though everything around her was beautiful and fine. She stood at the altar and felt like she was about to collapse.</p><p>She had felt this way, at varying intensities, for most of her adult life. She thought everyone did.</p><p>They don't.</p><h2>What Anxiety Actually Looks Like</h2><p>Anxiety disorder is not the same as being a worrier. It is not timidity or overthinking. It is a physiological response — your nervous system going into emergency mode when there is no emergency. Your body releasing stress hormones for threats that aren't there.</p><p>It can look like a racing heart and shortness of breath with no physical cause. It can be the inability to sleep because your mind won't stop catastrophising. It can be avoiding social situations because the thought of them makes you physically sick. It can be obsessive checking — doors, gas cookers, children — dozens of times a night.</p><h2>Why African Women Often Miss the Diagnosis</h2><p>We are taught to be strong. We are taught to manage. We are taught that our feelings are secondary to our responsibilities. So anxiety, for many African women especially, gets filed under <em>\"just stress\"</em> or <em>\"I need to pray more.\"</em></p><p>Years pass. Decades, sometimes.</p><h2>Anxiety Is Treatable</h2><p>This is important: anxiety is not a life sentence. With the right therapeutic support — and sometimes, in consultation with a medical doctor, medication — people recover. They live full, calm, present lives.</p><p>You are not destined to live in permanent emergency mode. <a href='/services/individual-counselling'>Counselling</a> can help you understand what's triggering your anxiety and build practical tools to manage it.</p>",
    "coverImage": "",
    "coverImageAlt": "A woman with her hand on her chest, eyes closed, trying to breathe",
    "categorySlug": "mental-wellness",
    "pillar": null,
    "topics": ["anxiety disorder"],
    "tags": ["anxiety", "mental health", "panic attacks", "women's health", "Nigeria", "therapy", "healing"],
    "type": "cluster",
    "status": "published",
    "source": "human",
    "scheduledFor": null,
    "publishedAt": 1652947200000,
    "readingTime": 5,
    "actualReadingTime": null,
    "metaTitle": "Anxiety Is Not Just Worrying Too Much | Pain2Purpose",
    "metaDescription": "Anxiety is a real, diagnosable condition — not just overthinking. Sandra Opara explains what anxiety truly is and why so many African women suffer in silence.",
    "focusKeyword": "anxiety disorder symptoms treatment Nigeria",
    "isFeatured": false,
    "isArchived": false
  },
  {
    "title": "The Day I Decided to Stop Being Strong",
    "slug": "the-day-i-decided-to-stop-being-strong",
    "excerpt": "There is a kind of strength that is really just fear dressed in armour. I know because I wore it for years. This is the story of the day I finally took it off.",
    "content": "<p>For years, I was the strong one.</p><p>I was the one people called when things fell apart. The one who sat with the grieving widow, who counselled the couple on the edge of divorce, who held space for everyone else's pain — and then drove home alone, walked into my house, and kept moving.</p><p>I had convinced myself that this was strength.</p><p>I was wrong.</p><h2>What \"Being Strong\" Cost Me</h2><p>There is a kind of strength that is really just fear dressed in armour. Fear of being seen as weak. Fear that if you fall apart, no one will be there to put you back together. Fear that your vulnerability will somehow invalidate your ability to help others.</p><p>I carried that fear for years. And it was exhausting.</p><p>I remember sitting in my car one evening outside my house. I had just come from a particularly difficult session with a client. I sat there for twenty minutes, not wanting to go inside. Not wanting to perform being fine for one more minute.</p><p>I cried. Not for the client. For me.</p><h2>Therapists Need Therapy Too</h2><p>Yes, I said it. I have sat in a therapist's chair myself. I have been the one saying, <em>\"I don't know how to carry this anymore.\"</em></p><p>And it was one of the most important things I ever did for myself — and, ultimately, for the people I serve.</p><p>You cannot pour from empty. You cannot offer real empathy if you are numb to your own pain.</p><h2>Permission to Be Human</h2><p>If you are the strong one — the one everyone leans on — I want to give you permission today. Permission to not be okay. Permission to ask for help. Permission to stop performing strength and start practicing it.</p><p>Real strength is not the absence of need. It is the courage to admit it.</p><blockquote><p><em>\"You don't have to be the hero of everyone else's story while slowly disappearing from your own.\"</em></p></blockquote>",
    "coverImage": "",
    "coverImageAlt": "A woman with her forehead resting on her hands, quiet moment of surrender",
    "categorySlug": "sandras-journal",
    "pillar": null,
    "topics": ["self care for helpers", "vulnerability"],
    "tags": ["strength", "vulnerability", "self care", "burnout", "therapy", "counsellors", "healing"],
    "type": "insight",
    "status": "published",
    "source": "human",
    "scheduledFor": null,
    "publishedAt": 1659168000000,
    "readingTime": 5,
    "actualReadingTime": null,
    "metaTitle": "The Day I Decided to Stop Being Strong | Pain2Purpose",
    "metaDescription": "There's a kind of strength that is just fear in disguise. Sandra Opara shares her personal story of choosing vulnerability over performance — and why it healed her.",
    "focusKeyword": "letting go of being strong vulnerability healing",
    "isFeatured": false,
    "isArchived": false
  },
  {
    "title": "Raising Children in a Broken Home — Without Breaking Them",
    "slug": "raising-children-in-a-broken-home",
    "excerpt": "When a marriage ends, people worry about the adults. But the children are watching everything. Here is what they need from you — even when you have nothing left to give.",
    "content": "<p>Tunde was seven when his parents separated. He stopped speaking for two weeks.</p><p>His teacher noticed first.</p><h2>Children Carry What We Don't Say</h2><p>Children are extraordinarily perceptive. They feel the tension before the argument. They hear the whispers behind closed doors. They watch your face when you think they're not looking.</p><p>And when a family falls apart — no matter how carefully the adults try to shield them — children know. What they don't always know is what it means. And in the absence of explanation, they fill the gap with fear, guilt, and confusion.</p><h2>What Parents Often Get Wrong</h2><p>The two most common mistakes I see in post-separation parenting are using children as messengers between two adults who can no longer speak to each other, and speaking badly about the other parent in the child's hearing.</p><p>Both damage children deeply. A child is made of both parents. When you attack the other parent, part of the child hears: <em>part of me is terrible.</em></p><h2>What Children Actually Need</h2><p>They need stability — a routine that signals that their world has not completely collapsed. They need honesty in age-appropriate language: <em>\"Mummy and Daddy are not going to live together anymore, but we both love you and that will never change.\"</em></p><p>They need permission to grieve. They need permission to still love both parents without guilt.</p><p>And they need to see, over time, that adults can fall apart and rebuild.</p>",
    "coverImage": "",
    "coverImageAlt": "A child sitting between two empty chairs, looking at the floor",
    "categorySlug": "autism-and-family",
    "pillar": null,
    "topics": ["parenting after separation", "children and divorce"],
    "tags": ["parenting", "divorce", "children", "family", "separation", "emotional health", "counselling"],
    "type": "cluster",
    "status": "published",
    "source": "human",
    "scheduledFor": null,
    "publishedAt": 1663833600000,
    "readingTime": 6,
    "actualReadingTime": null,
    "metaTitle": "Raising Children in a Broken Home — Without Breaking Them | Pain2Purpose",
    "metaDescription": "When a marriage ends, children carry what's not said. Sandra Opara shares what children truly need from parents during and after family separation.",
    "focusKeyword": "parenting children after divorce Nigeria",
    "isFeatured": false,
    "isArchived": false
  },
  {
    "title": "Forgiveness Is Not for Them",
    "slug": "forgiveness-is-not-for-them",
    "excerpt": "She looked me dead in the eyes and said, 'Why should I forgive him? He has never even apologised.' I told her the truth: forgiveness is not a gift you give to the person who hurt you.",
    "content": "<p>She looked me dead in the eyes and said, <em>\"Why should I forgive him? He has never even apologised.\"</em></p><p>I didn't argue with her. I understood completely.</p><p>But I told her the truth: forgiveness is not a gift you give to the person who hurt you.</p><p>It is a gift you give yourself.</p><h2>What Unforgiveness Actually Does to You</h2><p>Carrying unforgiveness is like drinking poison and waiting for the other person to get sick. While you are replaying the hurt, while you are rehearsing what you should have said, while you are keeping the wound open so it stays fresh — the person who hurt you is often sleeping soundly.</p><p>Unforgiveness lives in your body. Bitterness and resentment are linked to elevated stress hormones, disrupted sleep, and weakened immunity.</p><h2>What Forgiveness Is Not</h2><p>Forgiveness is not saying what happened was okay. It is not resuming the relationship. It is not reconciliation — reconciliation requires two willing people. Forgiveness requires only one: you.</p><p>You can forgive someone and still never speak to them again. Forgiveness simply means: <em>I am releasing the grip this has on me. I am choosing not to let your actions define the rest of my story.</em></p><h2>How You Begin</h2><p>You don't have to feel it to choose it. Forgiveness is first a decision, then a process, then — eventually — a feeling. Start with the decision.</p>",
    "coverImage": "",
    "coverImageAlt": "Open hands releasing a bird into the sky",
    "categorySlug": "healing-and-recovery",
    "pillar": null,
    "topics": ["forgiveness and healing"],
    "tags": ["forgiveness", "healing", "letting go", "bitterness", "mental health", "therapy", "recovery"],
    "type": "insight",
    "status": "published",
    "source": "human",
    "scheduledFor": null,
    "publishedAt": 1668412800000,
    "readingTime": 5,
    "actualReadingTime": null,
    "metaTitle": "Forgiveness Is Not for Them | Pain2Purpose",
    "metaDescription": "Forgiveness is not a gift to the person who hurt you — it's a gift to yourself. Sandra Opara explains what forgiveness truly means and how to begin.",
    "focusKeyword": "forgiveness healing mental health",
    "isFeatured": false,
    "isArchived": false
  },
  {
    "title": "When the Church Doesn't Know What to Do With Your Pain",
    "slug": "when-the-church-doesnt-know-what-to-do-with-your-pain",
    "excerpt": "Brother Emmanuel stood up in testimony service and said he had been healed of depression. Three months later, he took his own life. The church had no framework for what he was carrying.",
    "content": "<p>Brother Emmanuel was one of the most cheerful voices in the choir.</p><p>He stood up one Sunday in testimony service and declared that God had delivered him from depression. The church erupted. People shouted and praised. The pastor prayed over him with oil.</p><p>Three months later, Brother Emmanuel took his own life.</p><p>I share this story because his family believe his story deserves to be told. Because they believe the church failed him. Not from malice, but from ignorance.</p><h2>The Gap Between Faith and Mental Health</h2><p>The Nigerian church has historically treated mental illness as either a spiritual problem or a sign of weak faith. Prayer and fasting are prescribed for conditions that also require clinical attention.</p><p>This is not an attack on faith. I am a woman of faith. Prayer is real.</p><p>But Brother Emmanuel's brain also needed medical and therapeutic support. And the community he trusted most did not have the language for that.</p><h2>What Churches Can Do Better</h2><p>Faith communities are uniquely positioned to be first responders to mental health crises. It starts with education. With leaders learning to recognize signs of serious mental illness. With removing the shame around seeking professional support.</p><h2>You Can Have Both</h2><p>You can pray and see a therapist. You can believe in healing and also take your medication. God and therapy are not rivals.</p>",
    "coverImage": "",
    "coverImageAlt": "Empty church pews with light streaming through stained glass",
    "categorySlug": "mental-wellness",
    "pillar": null,
    "topics": ["faith and mental health"],
    "tags": ["church", "faith", "depression", "mental health Nigeria", "stigma", "suicide prevention", "therapy"],
    "type": "observant",
    "status": "published",
    "source": "human",
    "scheduledFor": null,
    "publishedAt": 1674892800000,
    "readingTime": 6,
    "actualReadingTime": null,
    "metaTitle": "When the Church Doesn't Know What to Do With Your Pain | Pain2Purpose",
    "metaDescription": "Faith communities are often the first place people turn — but are they equipped? Sandra Opara addresses the gap between church culture and mental health care in Nigeria.",
    "focusKeyword": "faith mental health Nigeria church",
    "isFeatured": true,
    "isArchived": false
  },
  {
    "title": "The Quiet Grief of Miscarriage",
    "slug": "the-quiet-grief-of-miscarriage",
    "excerpt": "Nobody sends flowers. Nobody gives you time off work. Nobody says 'I'm sorry for your loss' — because to the world, there was no person yet. But you know what you lost.",
    "content": "<p>Nobody sends flowers for a miscarriage.</p><p>Nobody organises a condolence visit. Nobody gives you time off work. Nobody says, <em>\"I am so sorry for your loss\"</em> — because to the world around you, there was no person yet.</p><p>But you know what you lost. A future.</p><h2>The Grief That Has No Ceremony</h2><p>Miscarriage is one of the most common and most invisible griefs in the world. And yet the grief is almost universally suffered in silence.</p><p>In Nigeria especially, where pregnancy is often tied to a woman's worth, a miscarriage can carry layers of shame, fear, and spiritual questioning that make it even harder to process.</p><p>I have sat with women who blamed themselves. Who were told by relatives that it happened for a reason, or that they should just try again.</p><h2>What the Grieving Mother Needs</h2><p>She needs to be believed — that her loss is real, that her grief is valid, that a pregnancy of eight weeks was already a love story.</p><p>She needs space to grieve without a timeline. Without being rushed back to hope before she has finished with sorrow.</p><p>Please know you don't have to do it silently. <a href='/services/grief-and-loss-support'>Our grief support sessions</a> are a safe, private space for this exact kind of pain.</p>",
    "coverImage": "",
    "coverImageAlt": "A pair of tiny empty shoes on a windowsill",
    "categorySlug": "grief-and-loss",
    "pillar": null,
    "topics": ["pregnancy loss", "miscarriage grief"],
    "tags": ["miscarriage", "pregnancy loss", "grief", "women", "healing", "mental health", "Nigeria"],
    "type": "insight",
    "status": "published",
    "source": "human",
    "scheduledFor": null,
    "publishedAt": 1679212800000,
    "readingTime": 5,
    "actualReadingTime": null,
    "metaTitle": "The Quiet Grief of Miscarriage | Pain2Purpose",
    "metaDescription": "Nobody sends flowers for a miscarriage. Sandra Opara names the invisible grief of pregnancy loss — and speaks to the women who are suffering in silence.",
    "focusKeyword": "miscarriage grief support Nigeria",
    "isFeatured": false,
    "isArchived": false
  },
  {
    "title": "Stop Telling Your Child to Man Up",
    "slug": "stop-telling-your-child-to-man-up",
    "excerpt": "Chidi was nine when his father told him men don't cry. At thirty-four, Chidi doesn't cry. He also doesn't feel. He doesn't ask for help. And he is slowly falling apart.",
    "content": "<p>Chidi was nine years old when his father caught him crying over a scraped knee and said, <em>\"Stop that. Men don't cry.\"</em></p><p>Chidi is now thirty-four. He doesn't cry. He is very good at not crying.</p><p>He is also very good at not asking for help, not admitting he is struggling, and he is slowly, quietly, falling apart.</p><h2>What We Do to Boys</h2><p>We train boys — in Nigerian homes — to suppress emotion so thoroughly that by adulthood, many of them have no healthy language for what they feel.</p><p>We tell them strong. We tell them don't be soft. We tell them be a man — as if manhood is achieved by feeling less.</p><p>And then we are surprised when they can't communicate in their marriages. When they react to emotional pain with aggression or withdrawal.</p><h2>Emotion Is Not Gender-Specific</h2><p>Every human being has an emotional life. Feelings do not check gender at the door. When we deny boys that permission, we are not making them stronger. We are making them more dangerous — to themselves and to the people who love them.</p><h2>What to Say Instead</h2><p>Tell your son: <em>\"It's okay to cry. Tears don't make you less of anything.\"</em> Tell him: <em>\"Strong people ask for help.\"</em></p>",
    "coverImage": "",
    "coverImageAlt": "A father kneeling to eye level with a young son",
    "categorySlug": "autism-and-family",
    "pillar": null,
    "topics": ["raising boys", "emotional intelligence"],
    "tags": ["parenting", "boys", "toxic masculinity", "emotional health", "fathers", "Nigeria", "counselling"],
    "type": "observant",
    "status": "published",
    "source": "human",
    "scheduledFor": null,
    "publishedAt": 1683792000000,
    "readingTime": 5,
    "actualReadingTime": null,
    "metaTitle": "Stop Telling Your Child to Man Up | Pain2Purpose",
    "metaDescription": "When we tell boys not to cry, we are not making them stronger — we are making them emotionally unavailable. Sandra Opara challenges how we raise Nigerian boys.",
    "focusKeyword": "raising emotionally healthy boys Nigeria",
    "isFeatured": false,
    "isArchived": false
  },
  {
    "title": "Trauma Doesn't Always Look Like Trauma",
    "slug": "trauma-doesnt-always-look-like-trauma",
    "excerpt": "Trauma is not always a dramatic event. Sometimes it is years of being told you are not enough. Sometimes it is the home that was never quite safe. Sometimes it is the childhood nobody would believe was bad.",
    "content": "<p>When people hear the word trauma, they often think of war. Of accidents. Of violence witnessed with their own eyes.</p><p>They don't think of the child who grew up in a home where love was conditional. Who learned, very early, to be small — to take up less space, to need less, to earn the right to be loved.</p><p>But that is trauma too.</p><h2>The Trauma That Has No Name</h2><p>Complex trauma happens when the wound is not a single event but a pattern. Years of emotional neglect. Living in a home where criticism was the primary language.</p><p>These experiences produce hypervigilance disguised as being responsible. People-pleasing disguised as being kind. Self-criticism so constant that it no longer has a sound — it is just the air you breathe.</p><h2>Naming It Is the Beginning</h2><p>Naming a thing does not trap you in it. It does the opposite — it gives you the ability to see it from the outside, which is the first step to working through it.</p><p>You are someone who adapted brilliantly to an environment that was not safe. And now, those adaptations no longer serve you.</p><p><a href='/services/individual-counselling'>Therapy</a> can help you understand the patterns and update the story.</p>",
    "coverImage": "",
    "coverImageAlt": "A person looking into the distance, expression unreadable",
    "categorySlug": "healing-and-recovery",
    "pillar": null,
    "topics": ["complex trauma", "childhood trauma"],
    "tags": ["trauma", "complex trauma", "childhood", "mental health", "therapy", "healing", "self awareness"],
    "type": "pillar",
    "status": "published",
    "source": "human",
    "scheduledFor": null,
    "publishedAt": 1688630400000,
    "readingTime": 6,
    "actualReadingTime": null,
    "metaTitle": "Trauma Doesn't Always Look Like Trauma | Pain2Purpose",
    "metaDescription": "Trauma isn't always a dramatic event. Sandra Opara explores the quiet, invisible forms of trauma that shape adult behaviour — and how to begin healing.",
    "focusKeyword": "complex trauma signs and symptoms",
    "isFeatured": true,
    "isArchived": false
  },
  {
    "title": "When He Hits You, It Is Not Love",
    "slug": "when-he-hits-you-it-is-not-love",
    "excerpt": "She said, 'But he always apologises. He cries after.' I've heard this more times than I can count. The apology is part of the cycle — not proof that it won't happen again.",
    "content": "<p>She sat across from me holding her bag tightly in her lap. She had foundation on her arm.</p><p><em>\"But he always apologises,\"</em> she said. <em>\"He cries after. He says he doesn't know what came over him.\"</em></p><p>The apology is part of the cycle. It is not proof that it won't happen again. It is part of why it happens again.</p><h2>The Cycle of Abuse</h2><p>There is a pattern in abusive relationships: tension builds, the incident occurs, the honeymoon phase follows — tearful apologies, gifts, promises that feel sincere. And then the tension begins to build again.</p><p>The honeymoon phase is not redemption. It is reset.</p><h2>Why Women Stay</h2><p>Women stay because of children. Because of finances. Because of family pressure. Because he controls their access to money. Because he has isolated them from the people who could help.</p><h2>What I Want You to Know</h2><p>Love does not leave marks on your body. Love does not make you afraid in your own home. You deserve to be safe. That is not a high standard. That is the minimum.</p><p>If you are in an abusive situation and need to speak to someone, please reach out. <a href='/services/individual-counselling'>Our sessions are confidential.</a></p>",
    "coverImage": "",
    "coverImageAlt": "A woman sitting alone by a window, looking down at her hands",
    "categorySlug": "healing-and-recovery",
    "pillar": null,
    "topics": ["domestic violence", "abusive relationships"],
    "tags": ["domestic violence", "abuse", "relationships", "women", "safety", "Nigeria", "healing", "counselling"],
    "type": "observant",
    "status": "published",
    "source": "human",
    "scheduledFor": null,
    "publishedAt": 1692864000000,
    "readingTime": 5,
    "actualReadingTime": null,
    "metaTitle": "When He Hits You, It Is Not Love | Pain2Purpose",
    "metaDescription": "The apology is part of the cycle — not proof that it won't happen again. Sandra Opara speaks directly to women in abusive relationships in Nigeria.",
    "focusKeyword": "domestic violence Nigeria abusive relationship help",
    "isFeatured": false,
    "isArchived": false
  },
  {
    "title": "The Pressure to Be Married by 30",
    "slug": "pressure-to-be-married-by-30",
    "excerpt": "Aunty Chioma calls every December to ask the same question. The Christmas table has become a tribunal. If you know, you know.",
    "content": "<p>Aunty Chioma calls every December. Same question. Same tone.</p><p><em>\"My dear, no man yet? You are not getting younger, you know.\"</em></p><p>The Christmas table has become a tribunal. If you know, you know.</p><h2>What the Pressure Actually Does</h2><p>The psychological damage of sustained social pressure around marriage is real. I have worked with women in their late twenties who describe a constant background anxiety — a low hum of shame. Who end up in marriages that were wrong for them because the alternative felt like failure.</p><h2>Singleness Is Not a Waiting Room</h2><p>Your life is not paused until someone chooses you. The years you are living right now count. They are not rehearsal.</p><p>Who you are becoming in this season matters. The wisdom you are building, the relationship you are developing with yourself — these things are the foundation of everything that comes after.</p><h2>A Word About Standards</h2><p>Lowering your standards to meet a deadline is not wisdom — it is panic. And panic makes terrible decisions.</p><p>Know what you need. refuse to apologise for it, regardless of what Aunty Chioma says in December.</p>",
    "coverImage": "",
    "coverImageAlt": "A confident woman sitting alone at a restaurant table, smiling",
    "categorySlug": "sandras-journal",
    "pillar": null,
    "topics": ["marriage pressure", "singleness"],
    "tags": ["marriage", "singleness", "pressure", "women", "Nigeria", "self worth", "society"],
    "type": "observant",
    "status": "published",
    "source": "human",
    "scheduledFor": null,
    "publishedAt": 1696492800000,
    "readingTime": 5,
    "actualReadingTime": null,
    "metaTitle": "The Pressure to Be Married by 30 | Pain2Purpose",
    "metaDescription": "Aunty Chioma calls every December with the same question. Sandra Opara talks about the mental health cost of marriage pressure — and why your season is your own.",
    "focusKeyword": "marriage pressure singleness Nigeria mental health",
    "isFeatured": false,
    "isArchived": false
  },
  {
    "title": "How to Support a Friend With Depression — Without Making It Worse",
    "slug": "how-to-support-a-friend-with-depression",
    "excerpt": "Your friend told you they are struggling. You want to help. You are terrified of saying the wrong thing. Here is what actually helps — and what quietly makes things harder.",
    "content": "<p>Your friend finally told you. You now know — your person is struggling with depression. And you want to help. And you are terrified of saying the wrong thing.</p><h2>What Helps</h2><p><strong>Simply being present without fixing.</strong> Sit with them. You do not have to have the right words. Often the most powerful thing is just: <em>I am here and I am not going anywhere.</em></p><p><strong>Asking instead of assuming.</strong> \"What do you need right now?\" is one of the most underrated questions in the world.</p><p><strong>Checking in consistently.</strong> Depression is not a one-time crisis. It is a season. Your consistency says more than your initial response.</p><h2>What Quietly Makes It Worse</h2><p>Telling them to snap out of it, to just pray or exercise or stay positive — these things communicate that their pain is unreasonable. This increases shame, not healing.</p><h2>And If You Are Worried About Their Safety</h2><p>If your friend is expressing thoughts of harming themselves, take it seriously. Ask them directly: <em>\"Are you thinking about suicide?\"</em> Help them access professional support immediately.</p>",
    "coverImage": "",
    "coverImageAlt": "Two friends sitting together on a park bench, one leaning on the other",
    "categorySlug": "mental-wellness",
    "pillar": null,
    "topics": ["supporting mental health", "friendship"],
    "tags": ["depression", "friendship", "support", "mental health", "suicide prevention", "how to help", "counselling"],
    "type": "cluster",
    "status": "published",
    "source": "human",
    "scheduledFor": null,
    "publishedAt": 1700294400000,
    "readingTime": 6,
    "actualReadingTime": null,
    "metaTitle": "How to Support a Friend With Depression — Without Making It Worse | Pain2Purpose",
    "metaDescription": "Your friend is struggling. You want to help. Sandra Opara explains what genuinely helps someone with depression — and what quietly makes things harder.",
    "focusKeyword": "how to help a friend with depression",
    "isFeatured": false,
    "isArchived": false
  },
  {
    "title": "The Invisible Load of the African Mother",
    "slug": "invisible-load-of-the-african-mother",
    "excerpt": "She wakes before everyone. She sleeps after everyone. She carries the calendar of the entire household in her head. And when she finally breaks down, someone asks — 'But what's wrong? You have everything.'",
    "content": "<p>She wakes before everyone. Preps breakfast, reminds her husband about his meeting, handles school fees, gets to the office looking like none of that happened. She sleeps after everyone.</p><p>She carries the entire household in her head — the invisible mental load that no one assigns her officially but everyone benefits from silently.</p><h2>The Mental Load Nobody Names</h2><p>The mental load refers to the cognitive labour of managing a household. In many African households, it is compounded by extended family obligations and cultural expectations of selflessness.</p><h2>What Happens When It's Ignored</h2><p>Burnout. The kind that hides under resentment that grows slowly. The kind that shows up in her body — chronic headaches, the inexplicable exhaustion that no amount of sleep fixes.</p><h2>This Is Not Meant to Be Carried Alone</h2><p>To every African mother: what you are carrying is real. Your exhaustion is legitimate. Your need for rest and help is not selfishness. It is survival.</p><p><a href='/services/individual-counselling'>Counselling can be the first step in reclaiming yourself.</a></p>",
    "coverImage": "",
    "coverImageAlt": "A tired mother leaning against the kitchen counter with closed eyes",
    "categorySlug": "sandras-journal",
    "pillar": null,
    "topics": ["motherhood", "burnout", "mental load"],
    "tags": ["mothers", "burnout", "African mothers", "Nigeria", "mental health", "marriage", "self care"],
    "type": "observant",
    "status": "published",
    "source": "human",
    "scheduledFor": null,
    "publishedAt": 1705046400000,
    "readingTime": 6,
    "actualReadingTime": null,
    "metaTitle": "The Invisible Load of the African Mother | Pain2Purpose",
    "metaDescription": "She carries the entire household in her head — and nobody notices. Sandra Opara names the invisible mental load of the African mother and the cost of carrying it alone.",
    "focusKeyword": "African mother burnout mental health",
    "isFeatured": true,
    "isArchived": false
  },
  {
    "title": "What Grief Looks Like in Year Two",
    "slug": "what-grief-looks-like-in-year-two",
    "excerpt": "Everyone shows up in the first week. By month three, life has moved on for everyone else. By year two, people expect you to be over it. But grief doesn't follow the schedule people prefer.",
    "content": "<p>Everyone shows up in the first week. By year two — two years after you buried the person you loved — there is a peculiar expectation in the air: <em>Surely you should be over it by now.</em></p><p>You are not over it. Nothing is wrong with you.</p><h2>What Grief Actually Looks Like in Year Two</h2><p>Year two of grief is, for many, harder than year one. In year one, the shock serves as a buffer. In year two, the numbness has lifted and the reality has settled. You are in the long, quiet ache of absence.</p><h2>There Is No Timeline</h2><p>Grief is not linear. It does not conclude. It changes shape over time. The grief is the love. It is the evidence that this person mattered.</p><p>Give yourself the grace that others have forgotten to extend. <a href='/services/grief-and-loss-support'>Grief counselling</a> is here whenever you need it.</p>",
    "coverImage": "",
    "coverImageAlt": "A person holding a photo frame, looking out the window",
    "categorySlug": "grief-and-loss",
    "pillar": null,
    "topics": ["grief timeline", "prolonged grief"],
    "tags": ["grief", "loss", "bereavement", "healing", "mental health", "counselling", "widowhood"],
    "type": "insight",
    "status": "published",
    "source": "human",
    "scheduledFor": null,
    "publishedAt": 1708588800000,
    "readingTime": 5,
    "actualReadingTime": null,
    "metaTitle": "What Grief Looks Like in Year Two | Pain2Purpose",
    "metaDescription": "By year two, people expect you to be over it. Sandra Opara speaks honestly about what grief looks like in the second year — and why there is no right timeline.",
    "focusKeyword": "grief after bereavement year two healing",
    "isFeatured": false,
    "isArchived": false
  },
  {
    "title": "My Autistic Child Is Not Broken — Stop Praying for a Cure",
    "slug": "my-autistic-child-is-not-broken-stop-praying-for-cure",
    "excerpt": "A woman stood up at a prayer meeting and asked the congregation to pray that God would 'heal' her son of autism. Her son, who can hear, was sitting right beside her.",
    "content": "<p>A woman asked a prayer meeting to pray that God would heal her son of autism. Her son — who is nonverbal but can hear everything — was sitting right beside her.</p><h2>Autism Is Not a Spiritual Problem</h2><p>Let me be direct: autism is a neurological difference, not a curse. When we treat autism as something to be exorcised, we send a message — to the child and to ourselves — that who they are is unacceptable. That their existence is a mistake.</p><h2>What Your Child Actually Needs</h2><p>Early structured support. Speech therapy, occupational therapy. A school environment that understands their learning style. Your child needs you to become the expert on <em>them</em>. Their triggers. Their joy.</p><h2>And What You Need</h2><p>You need community with other parents who understand. <a href='/services/autism-family-support'>Our family support sessions</a> are designed for exactly this journey.</p>",
    "coverImage": "",
    "coverImageAlt": "A parent and child building something together on the floor",
    "categorySlug": "autism-and-family",
    "pillar": null,
    "topics": ["autism acceptance", "parenting autistic children"],
    "tags": ["autism", "neurodiversity", "parenting", "Nigeria", "family", "acceptance", "therapy", "faith"],
    "type": "observant",
    "status": "published",
    "source": "human",
    "scheduledFor": null,
    "publishedAt": 1711785600000,
    "readingTime": 6,
    "actualReadingTime": null,
    "metaTitle": "My Autistic Child Is Not Broken — Stop Praying for a Cure | Pain2Purpose",
    "metaDescription": "Autism is not a curse or a punishment. Sandra Opara challenges the prayer-for-cure approach and explains what autistic children in Nigeria actually need.",
    "focusKeyword": "autism acceptance parenting Nigeria",
    "isFeatured": false,
    "isArchived": false
  },
  {
    "title": "The Art of Doing Nothing — Why Rest Is Productive",
    "slug": "the-art-of-doing-nothing-rest-is-productive",
    "excerpt": "We have built an entire culture around busyness as a badge of honour. But your body keeps the score — and one day, it will make you rest whether you planned to or not.",
    "content": "<p>I had a client who described her ideal weekend as \"productive.\" She had clean the house, cooked for the week, called six different relatives. Then she told me she hadn't truly rested in three years.</p><h2>The Busyness Badge</h2><p>We live in a culture that has made busyness a virtue. To rest is to be lazy. And the body keeps the score.</p><h2>What Rest Actually Is</h2><p>Rest is not the absence of productivity. It is a form of productivity — one that operates at the level of your nervous system and immune function. Rest also looks like sitting in silence. Like staring at the ceiling without guilt.</p><h2>What Chronic Rest-Deprivation Produces</h2><p>Irritability. Reduced empathy. Decision fatigue. And eventually, breakdown. Your body will make you rest. It is not a question of if but when.</p><h2>Permission, Granted</h2><p>You have permission to rest. Not when you've earned it. Now.</p>",
    "coverImage": "",
    "coverImageAlt": "A person lying in a hammock outdoors, eyes closed, peaceful",
    "categorySlug": "mental-wellness",
    "pillar": null,
    "topics": ["rest and mental health", "burnout prevention"],
    "tags": ["rest", "burnout", "mental health", "productivity", "self care", "Nigeria", "wellness"],
    "type": "cluster",
    "status": "published",
    "source": "human",
    "scheduledFor": null,
    "publishedAt": 1714204800000,
    "readingTime": 5,
    "actualReadingTime": null,
    "metaTitle": "The Art of Doing Nothing — Why Rest Is Productive | Pain2Purpose",
    "metaDescription": "We wear busyness like a badge — but your body will eventually force you to rest. Sandra Opara makes the case for deliberate rest as a mental health necessity.",
    "focusKeyword": "rest burnout mental health Nigeria",
    "isFeatured": false,
    "isArchived": false
  },
  {
    "title": "Therapy Is Not for Mad People",
    "slug": "therapy-is-not-for-mad-people",
    "excerpt": "In Nigeria, when you mention therapy, someone inevitably says: 'Are you mad? What will they think of you?' Let us dismantle that one, together.",
    "content": "<p>Therapy is not for mad people. Therapy is for humans.</p><h2>What Therapy Actually Is</h2><p>Therapy is a structured, safe space in which you talk to a trained professional about your inner world — your thoughts, your feelings, your patterns — and receive insight and tools that help you live better.</p><h2>Who Goes to Therapy</h2><p>Athletes managing performance anxiety. New mothers navigating identity shifts. People who have experienced loss. Some of the most self-aware people I know have been in therapy — because they chose to grow.</p><h2>The Nigerian Stigma Is Costing Lives</h2><p>People are suffering in silence — managing trauma by simply never talking about it. This is not strength. This is compounded suffering.</p><h2>You Don't Have to Wait for a Crisis</h2><p>You don't have to be diagnosable to benefit from therapy. You just have to be a human being who wants to live better.</p>",
    "coverImage": "",
    "coverImageAlt": "A calm, welcoming counselling office with two chairs facing each other",
    "categorySlug": "mental-wellness",
    "pillar": null,
    "topics": ["therapy stigma", "mental health access"],
    "tags": ["therapy", "counselling", "stigma", "Nigeria", "mental health", "wellbeing", "healing"],
    "type": "pillar",
    "status": "published",
    "source": "human",
    "scheduledFor": null,
    "publishedAt": 1717833600000,
    "readingTime": 5,
    "actualReadingTime": null,
    "metaTitle": "Therapy Is Not for Mad People | Pain2Purpose",
    "metaDescription": "In Nigeria, therapy still carries stigma. Sandra Opara dismantles the myth that counselling is for the mentally ill — and makes the case for seeking support before crisis.",
    "focusKeyword": "therapy stigma Nigeria mental health counselling",
    "isFeatured": true,
    "isArchived": false
  },
  {
    "title": "On Being Enough — Exactly as You Are",
    "slug": "on-being-enough-exactly-as-you-are",
    "excerpt": "Social media has created a hall of mirrors in which everyone else's life looks better than yours. But you are comparing your insides to their outsides — and that is never a fair fight.",
    "content": "<p>I want to talk about the quiet, persistent feeling of not being enough. Not successful enough. Not married enough. Just — not enough.</p><h2>The Hall of Mirrors</h2><p>Social media has constructed a hall of mirrors in which everyone else's life appears more polished. But you are comparing your insiders to their outsides. That is not a fair comparison.</p><h2>Where \"Not Enough\" Comes From</h2><p>In most cases, it is about what you were told in your formative years. The teenager whose achievements were met with <em>\"but could you have done better?\"</em> These early messages become the internal voice: <em>not yet, not quite, not enough.</em></p><h2>The Truth About Enoughness</h2><p>Enoughness is not a destination. It is a decision. You are enough right now, in this version of yourself. Grow from curiosity rather than self-punishment.</p>",
    "coverImage": "",
    "coverImageAlt": "A mirror reflection of a person smiling at themselves",
    "categorySlug": "resilience-and-growth",
    "pillar": null,
    "topics": ["self worth", "self acceptance"],
    "tags": ["self worth", "enough", "social media", "mental health", "self love", "personal growth", "Nigeria"],
    "type": "insight",
    "status": "published",
    "source": "human",
    "scheduledFor": null,
    "publishedAt": 1721462400000,
    "readingTime": 5,
    "actualReadingTime": null,
    "metaTitle": "On Being Enough — Exactly as You Are | Pain2Purpose",
    "metaDescription": "You're comparing your insides to their outsides — and it's never a fair fight. Sandra Opara explores the quiet epidemic of not-enoughness and how to break free.",
    "focusKeyword": "self worth self acceptance mental health",
    "isFeatured": false,
    "isArchived": false
  },
  {
    "title": "We Are Spiritual Beings Having a Human Experience",
    "slug": "spiritual-beings-human-experience",
    "excerpt": "Don't let your body dictate your experiences — let your spirit reign. For the most beautiful experiences in your short time on earth, allow your spirit to soar.",
    "content": "<p>We are spiritual beings having a human experience. Make it worthwhile.</p><p>Don't let your body dictate your experiences — let your spirit reign.</p><h2>Let Your Spirit Lead</h2><p>For the most beautiful experiences in your short time on earth, allow your spirit to soar. As you do, you'll unlock depths of joy, peace, and purpose that transcend the ordinary.</p><p>So often we live from the outside in — letting circumstances, opinions, and pain define who we are and what we're capable of. But when we begin to live from the inside out, something shifts. We stop reacting and start responding. We stop surviving and start truly living.</p><h2>What This Means in Practice</h2><p>Living as a spiritual being doesn't mean disconnecting from the real world. It means bringing a deeper awareness into your everyday moments — how you treat others, how you speak to yourself, how you respond when life gets hard.</p><p>It means asking not just \"what happened to me?\" but \"what is this teaching me?\" It means choosing growth over bitterness, purpose over pain, and love over fear — even when it's difficult.</p><p>If you're searching for that deeper sense of meaning and direction, <a href='/services/resilience-coaching'>resilience coaching</a> can help you reconnect with who you truly are beneath the weight of life's experiences.</p><p>In the end, I'm certain that your spirit will thank you for the incredible adventure.</p>",
    "coverImage": "/assets/images/blogs/spiritual-soar.jpg",
    "coverImageAlt": "Person standing peacefully in sunlight with eyes closed",
    "categorySlug": "resilience-and-growth",
    "pillar": null,
    "topics": ["spirituality and purpose"],
    "tags": ["spirituality", "purpose", "personal growth", "inspiration", "mindfulness", "self discovery"],
    "type": "micro",
    "status": "published",
    "source": "human",
    "scheduledFor": null,
    "publishedAt": 1723017600000,
    "readingTime": 2,
    "actualReadingTime": null,
    "metaTitle": "We Are Spiritual Beings Having a Human Experience | Pain2Purpose",
    "metaDescription": "Don't let your body dictate your experience. Sandra Opara reflects on what it means to let your spirit lead and unlock deeper joy, peace, and purpose in life.",
    "focusKeyword": "spiritual growth and purpose",
    "isFeatured": false,
    "isArchived": false
  },
  {
    "title": "Let's Create a Culture of Kindness Online",
    "slug": "culture-of-kindness-online",
    "excerpt": "Behind every digital gadget is a human being with real feelings. It's time we built a culture of kindness online — before our words cost someone their tomorrow.",
    "content": "<p>No jokes! It's time we realized that behind every digital gadget is a human being with real feelings.</p><p>Every comment, tweet, or post has the potential to uplift or crush someone's spirit. Unfortunately, online spaces often become breeding grounds for hate, bullying, and cruelty. We must change this narrative and build a culture of kindness online.</p><p>Think of the tragic case of Nigerian student Deborah Samuel, who was brutally attacked and killed after being accused of blasphemy in a WhatsApp group chat. Her story reminds us of how digital words can quickly translate into real-world violence.</p><p>Or consider Kenyan athlete Agnes Tirop, a celebrated runner who was found dead in her home, allegedly due to a toxic relationship fueled by online threats and abuse.</p><p>These are just a few of the many lives lost or severely impacted due to online hate and harassment. Many have silently suffered, their mental health deteriorating due to cyberbullying, public shaming, and cancel culture.</p><h2>Recognizing Online Unkindness</h2><p>Online unkindness can take different forms, many of which are normalized in digital interactions:</p><ul><li><strong>Cyberbullying</strong> — Direct insults, threats, and targeted harassment that cause emotional distress.</li><li><strong>Doxxing</strong> — Sharing someone's personal information online, exposing them to danger.</li><li><strong>Trolling</strong> — Posting inflammatory content meant to provoke reactions or humiliate others.</li><li><strong>Cancel Culture Without Mercy</strong> — Destroying reputations without allowing room for context or redemption.</li><li><strong>Passive Aggression &amp; Gaslighting</strong> — Using sarcasm and manipulation to make others feel small or question their reality.</li></ul><h2>How Do We Cultivate Kindness in Digital Spaces?</h2><h3>Pause Before You Post</h3><p>Ask yourself: Would I say this in person? How would I feel receiving this message? If it's not kind or constructive, it's better left unsaid.</p>",
    "coverImage": "/assets/images/blogs/kindness-online.jpg",
    "coverImageAlt": "Person looking at a phone screen with a thoughtful expression",
    "categorySlug": "mental-wellness",
    "pillar": null,
    "topics": ["online kindness"],
    "tags": ["cyberbullying", "online safety", "mental health", "digital wellness", "kindness", "social media"],
    "type": "observant",
    "status": "published",
    "source": "human",
    "scheduledFor": null,
    "publishedAt": 1726300800000,
    "readingTime": 5,
    "actualReadingTime": null,
    "metaTitle": "Let's Create a Culture of Kindness Online | Pain2Purpose",
    "metaDescription": "Behind every screen is a real human being. Sandra Opara explores how online cruelty damages mental health and how we can choose kindness in digital spaces.",
    "focusKeyword": "online kindness mental health",
    "isFeatured": false,
    "isArchived": false
  },
  {
    "title": "When Helping Hurts — The Problem With Enabling",
    "slug": "when-helping-hurts-the-problem-with-enabling",
    "excerpt": "She had been paying her adult son's rent for eight years. 'I just don't want him to suffer,' she said. But I could see it clearly: she was funding his refusal to grow.",
    "content": "<p>He was thirty-one. Healthy. Educated. And consistently unable to hold a job for more than three months, because he knew that no matter what happened, the money would come.</p><p><em>\"I just don't want him to suffer,\"</em> she said.</p><p>I could also see, very clearly, she was funding his inability to grow. Her help had become his obstruction.</p><h2>The Fine Line Between Support and Enabling</h2><p>Helping moves someone toward independence. Enabling removes the consequence that would otherwise motivate change.</p><h2>Why We Enable</h2><p>Most enabling is rooted in love, fear, and the inability to tolerate another person's discomfort. But the person we are rescuing never gets to discover that they are capable of more.</p><h2>Especially in Nigerian Families</h2><p>Loving someone well sometimes means allowing them to face a consequence that teaches them what your rescuing never could.</p>",
    "coverImage": "",
    "coverImageAlt": "A hand reaching out to help, but the other hand can do it alone",
    "categorySlug": "healing-and-recovery",
    "pillar": null,
    "topics": ["enabling", "family dynamics"],
    "tags": ["enabling", "family", "boundaries", "Nigeria", "relationships", "parenting", "mental health"],
    "type": "observant",
    "status": "published",
    "source": "human",
    "scheduledFor": 1727942400000,
    "readingTime": 5,
    "actualReadingTime": null,
    "metaTitle": "When Helping Hurts — The Problem With Enabling | Pain2Purpose",
    "metaDescription": "There's a difference between supporting someone and enabling them — and love can blur that line. Sandra Opara explores family enabling and why it has to change.",
    "focusKeyword": "enabling family relationships Nigeria boundaries",
    "isFeatured": false,
    "isArchived": false
  },
  {
    "title": "Love Those Who Love You",
    "slug": "love-those-who-love-you",
    "excerpt": "Ada sat in front of me, twisting her fingers and forcing a smile. 'He doesn't call unless he needs help… but I still care.' The one who genuinely loved her was in the friend zone. Sound familiar?",
    "content": "<p>Ada sat in front of me, twisting her fingers and forcing a smile.</p><p><em>\"He doesn't call unless he needs help… but I still care,\"</em> she said.</p><p>Meanwhile, Chike — the one who brings her food at work when she's too tired to cook, the one who prays with her, sends airtime randomly, and genuinely asks how her day went — was still in her friend zone. She told me, <em>\"He's too available… I don't feel butterflies.\"</em></p><p>Butterflies? Let's be clear: in matters of love, you are allowed to choose peace.</p><p><strong>Choose people who choose you. And no, it's not pride. It's preservation.</strong></p><h2>Why Loving Those Who Love You Heals You</h2><h3>Psychologically</h3><p>Loving those who love you regulates your mind. It gives your nervous system a break from overthinking, second-guessing, and trying to prove you're worthy. It silences that inner critic that says \"I'm not enough.\" You sleep better. You smile for real. You breathe again.</p><h3>Emotionally</h3><p>Safe love heals. You begin to laugh louder, love deeper, and walk taller. Instead of feeling anxious after every chat, you feel affirmed. You don't have to shrink to be loved. You don't have to beg to be seen.</p><h3>Spiritually</h3><p>God is love — and love is not manipulation. It is not withdrawal of affection. It is not stringing someone along. When you love someone who genuinely honours you, it reflects the kind of love God has for us: honest, gentle, and mutual.</p>",
    "coverImage": "/assets/images/blogs/healthy-love.jpg",
    "coverImageAlt": "Two people having a warm, supportive conversation",
    "categorySlug": "healing-and-recovery",
    "pillar": null,
    "topics": ["healthy relationships"],
    "tags": ["relationships", "self worth", "emotional health", "love", "attachment styles", "counselling", "healing"],
    "type": "insight",
    "status": "published",
    "source": "human",
    "scheduledFor": null,
    "publishedAt": 1730534400000,
    "readingTime": 6,
    "actualReadingTime": null,
    "metaTitle": "Love Those Who Love You | Pain2Purpose Counselling",
    "metaDescription": "Why do we chase people who don't choose us? Sandra Opara explores the psychology of unrequited love and why choosing peace over pressure is true healing.",
    "focusKeyword": "loving people who love you back",
    "isFeatured": true,
    "isArchived": false
  },
  {
    "title": "Understanding Postpartum Depression — It Is Not Baby Blues",
    "slug": "understanding-postpartum-depression",
    "excerpt": "She had a healthy baby. A supportive husband. A beautiful nursery. And she couldn't stop crying and didn't know why. She thought she was a terrible mother. She wasn't — she was unwell.",
    "content": "<p>Amaka had everything people told her she needed to be happy. Three weeks after delivery, she couldn't get out of bed. She couldn't stop crying. She felt nothing when she held her baby.</p><p>She thought she was a terrible mother. She was not. She was unwell.</p><h2>Baby Blues vs. Postpartum Depression</h2><p>Baby blues are common — affecting up to 80% of new mothers. Postpartum depression is different. It is a clinical condition. It produces profound exhaustion that is separate from sleep deprivation.</p><h2>Why Nigerian Mothers Suffer Alone</h2><p>In Nigerian culture, new motherhood is wrapped in celebration. Admitting you are struggling after a baby can feel like a betrayal of the gift you've been given. And so women suffer silently.</p><h2>This Is Treatable</h2><p><a href='/services/individual-counselling'>Postpartum depression responds very well to treatment.</a></p>",
    "coverImage": "",
    "coverImageAlt": "A new mother sitting in a dim room looking exhausted, baby asleep nearby",
    "categorySlug": "sandras-journal",
    "pillar": null,
    "topics": ["postpartum depression", "new mothers"],
    "tags": ["postpartum depression", "new mothers", "motherhood", "Nigeria", "mental health", "baby blues", "therapy"],
    "type": "cluster",
    "status": "published",
    "source": "human",
    "scheduledFor": null,
    "publishedAt": 1733558400000,
    "readingTime": 6,
    "actualReadingTime": null,
    "metaTitle": "Understanding Postpartum Depression — It Is Not Baby Blues | Pain2Purpose",
    "metaDescription": "Postpartum depression is not ingratitude — it is a medical condition. Sandra Opara explains the difference between baby blues and PPD, and why Nigerian mothers suffer in silence.",
    "focusKeyword": "postpartum depression Nigeria new mothers",
    "isFeatured": false,
    "isArchived": false
  },
  {
    "title": "I Am Not Having This Conversation",
    "slug": "i-am-not-having-this-conversation",
    "excerpt": "There comes a time when wisdom is not about knowing everything — but knowing what to ignore. The day I discovered the power of saying 'I am not having this conversation' changed everything.",
    "content": "<p>There comes a time in life when wisdom is not about knowing everything — but knowing what to ignore.</p><p>I remember the day I discovered the power of saying, <em>\"I am not having this conversation.\"</em></p><p>I was in church after service, waiting to greet the pastor, when Sister Blessing leaned in, eyes twinkling like someone with exclusive presidential gossip. \"Have you heard?\" she asked, lowering her voice like the Holy Spirit had just whispered breaking news to her.</p>",
    "coverImage": "/assets/images/blogs/boundaries.jpg",
    "coverImageAlt": "Person calmly walking away from a difficult situation",
    "categorySlug": "mental-wellness",
    "pillar": null,
    "topics": ["personal boundaries"],
    "tags": ["boundaries", "toxic conversations", "mental health", "self protection", "wisdom", "personal boundaries"],
    "type": "observant",
    "status": "published",
    "source": "human",
    "scheduledFor": null,
    "publishedAt": 1737360000000,
    "readingTime": 5,
    "actualReadingTime": null,
    "metaTitle": "I Am Not Having This Conversation | Pain2Purpose Counselling",
    "metaDescription": "Some conversations are traps. Sandra Opara uses humour and hard truth to show which discussions to walk away from — for your peace and your sanity.",
    "focusKeyword": "setting boundaries toxic conversations",
    "isFeatured": false,
    "isArchived": false
  },
  {
    "title": "The Grief of a Job Loss Nobody Takes Seriously",
    "slug": "grief-of-job-loss-nobody-takes-seriously",
    "excerpt": "In Nigeria, when a man loses his job, the condolence visits don't come. Nobody sits with him. People say 'you'll find another one' — as if that addresses the devastation happening inside.",
    "content": "<p>In Nigeria, when someone dies, the condolence visits pour in. When a man loses his job, none of that happens.</p><p>People say, <em>\"You'll find another one.\"</em> But what is happening inside him can be indistinguishable from grief.</p><h2>Why Job Loss Hits So Deep</h2><p>For many — men especially — what you do and who you are have become intertwined. Your identity, your standing in your community — all of it reshuffled overnight.</p><h2>You Are Not Your Employment Status</h2><p>Your value is not determined by your current payslip. Shame is the most expensive thing you can hold onto right now.</p><p><a href='/services/individual-counselling'>Counselling can be a space to process the grief.</a></p>",
    "coverImage": "",
    "coverImageAlt": "A man sitting at an empty desk, looking out the window",
    "categorySlug": "resilience-and-growth",
    "pillar": null,
    "topics": ["job loss", "unemployment grief"],
    "tags": ["job loss", "unemployment", "men mental health", "Nigeria", "grief", "resilience", "identity"],
    "type": "insight",
    "status": "published",
    "source": "human",
    "scheduledFor": null,
    "publishedAt": 1738310400000,
    "readingTime": 5,
    "actualReadingTime": null,
    "metaTitle": "The Grief of a Job Loss Nobody Takes Seriously | Pain2Purpose",
    "metaDescription": "Losing a job in Nigeria can be as devastating as any bereavement — but nobody treats it that way. Sandra Opara names the grief of unemployment and what it costs men's mental health.",
    "focusKeyword": "job loss mental health Nigeria men",
    "isFeatured": false,
    "isArchived": false
  },
  {
    "title": "You Cannot Pour From an Empty Cup — Caregiver Burnout Is Real",
    "slug": "caregiver-burnout-is-real",
    "excerpt": "She had been caring for her mother with dementia for four years without a break. She told me, 'I feel guilty even wanting a day off.' This is what nobody tells you about being the one who stays.",
    "content": "<p>She had been caring for her mother with dementia for four years. She told me, <em>\"I feel guilty even wanting a day off.\"</em></p><h2>What Caregiver Burnout Looks Like</h2><p>Caregiver burnout is what happens to a person who has given so much for so long that their reserves are genuinely depleted. It looks like resentment — not of the loved one, but of the situation.</p><h2>Why Caregivers Don't Ask for Help</h2><p>In African families, caregiving is treated as sacred duty. admission you are struggling is to admit you don't love enough. This framework is not sustainable.</p><h2>What Sustainable Caregiving Requires</h2><p>Respite — scheduled time away without guilt. You cannot pour from an empty cup. Taking care of yourself is not betraying the person you love.</p>",
    "coverImage": "",
    "coverImageAlt": "An exhausted caregiver leaning against a wall in a hallway",
    "categorySlug": "healing-and-recovery",
    "pillar": null,
    "topics": ["caregiver burnout"],
    "tags": ["caregiving", "burnout", "dementia", "family", "mental health", "women", "Nigeria", "self care"],
    "type": "cluster",
    "status": "published",
    "source": "human",
    "scheduledFor": null,
    "publishedAt": 1739520000000,
    "readingTime": 5,
    "actualReadingTime": null,
    "metaTitle": "You Cannot Pour From an Empty Cup — Caregiver Burnout Is Real | Pain2Purpose",
    "metaDescription": "Four years of caregiving, no break, and she felt guilty for wanting one. Sandra Opara addresses caregiver burnout in Nigerian families — and why the caregiver matters too.",
    "focusKeyword": "caregiver burnout mental health Nigeria",
    "isFeatured": false,
    "isArchived": false
  },
  {
    "title": "Finding Purpose After Loss — A Journey Through Widowhood",
    "slug": "finding-purpose-after-loss-widowhood",
    "excerpt": "Your scars, spots, wrinkles, and stretch marks tell stories of life — of resilience and strength. Don't compare your behind-the-scenes to everyone else's highlight reel.",
    "content": "<p>Loss has a way of making the world go completely silent — and then unbearably loud, all at once.</p><p>Widowhood is one of the most profound griefs a person can carry. It is not just the loss of a person. It is the loss of a future you had already begun to imagine. It is waking up and reaching for someone who is no longer there. It is learning how to be one, when you had spent years learning how to be two.</p><h2>You Are Not Broken — You Are Becoming</h2><p>If you are walking through this season right now, I want you to hear this clearly: what you are feeling is not weakness. It is love in its rawest form — and love that deep deserves to be grieved fully.</p><p>But grief, while necessary, is not the final destination. It is the road.</p><p>Your scars, spots, wrinkles, and stretch marks tell stories of life — of resilience, of strength. Don't compare your behind-the-scenes moments to everyone else's highlight reels. Your journey is not behind. It is simply different.</p><h2>When Pain Becomes Purpose</h2><p>I have sat with many women who walked through the valley of widowhood and came out the other side not the same as they were before — but more themselves than they had ever been.</p><p>They discovered strengths they didn't know they had. They built communities for others walking the same road. They turned their grief into advocacy, their loss into legacy.</p><p>This is not toxic positivity. This is not telling you to \"get over it\" or \"move on.\" This is the truth that purpose can be found even in the deepest pain — not despite it, but often <em>because</em> of it.</p><h2>You Don't Have to Walk This Alone</h2><p>One of the most important things I've learned in years of <a href='/services/grief-and-loss-support'>grief counselling</a> is that healing is not a solo sport. It was never meant to be.</p><p>Community matters. Professional support matters. Allowing yourself to be held by those who understand matters.</p><p>If you are navigating loss and... [truncated] ",
    "coverImage": "/assets/images/blogs/widowhood-journey.jpg",
    "coverImageAlt": "A person sitting quietly by a window in contemplation",
    "categorySlug": "grief-and-loss",
    "pillar": null,
    "topics": ["grief and widowhood"],
    "tags": ["grief", "widowhood", "loss", "purpose", "healing", "resilience", "mental health support"],
    "type": "pillar",
    "status": "published",
    "source": "human",
    "scheduledFor": null,
    "publishedAt": 1741161600000,
    "readingTime": 5,
    "actualReadingTime": null,
    "metaTitle": "Finding Purpose After Loss — A Journey Through Widowhood | Pain2Purpose",
    "metaDescription": "Loss can feel like the end. Sandra Opara shares how pain, when processed with courage and support, can become the very foundation of a purposeful life.",
    "focusKeyword": "finding purpose after grief and loss",
    "isFeatured": true,
    "isArchived": false
  },
  {
    "title": "A Letter to the Teenager Who Feels Like Too Much",
    "slug": "letter-to-teenager-who-feels-like-too-much",
    "excerpt": "You are not dramatic. You are not too sensitive. You are not a problem to be managed. You are a young person in an overwhelming world — and someone needs to say: you are not too much. You are exactly enough.",
    "content": "<p>Dear Teenager, I am writing to you because I wonder if anyone is saying this to you: You are not too much.</p><h2>What Teenagers Are Carrying Right Now</h2><p>Comparison is now constant and inescapable. Add to this academic pressure and identity questions — you are carrying a great deal.</p><h2>Your Feelings Are Not a Malfunction</h2><p>Feelings are information — they are telling you something important about what you need. The goal is not to stop feeling, but to understand what you feel.</p><h2>Tell Someone</h2><p>Find one trusted adult — a counsellor, a teacher who gets it. You were not designed to carry this alone. <a href='/services/individual-counselling'>Counselling can help.</a></p>",
    "coverImage": "",
    "coverImageAlt": "A teenager sitting by a window looking out, pensive",
    "categorySlug": "sandras-journal",
    "pillar": null,
    "topics": ["teen mental health"],
    "tags": ["teenagers", "mental health", "anxiety", "adolescence", "Nigeria", "youth", "self worth", "parenting"],
    "type": "insight",
    "status": "published",
    "source": "human",
    "scheduledFor": null,
    "publishedAt": 1743580800000,
    "readingTime": 5,
    "actualReadingTime": null,
    "metaTitle": "A Letter to the Teenager Who Feels Like Too Much | Pain2Purpose",
    "metaDescription": "You are not dramatic. You are not too sensitive. Sandra Opara writes directly to the teenagers carrying more than anyone knows — and reminds them they are not alone.",
    "focusKeyword": "teen mental health Nigeria anxiety adolescence",
    "isFeatured": false,
    "isArchived": false
  },
  {
    "title": "Your Wipers — Finding Hope in Life's Storms",
    "slug": "your-wipers-finding-hope-in-lifes-storms",
    "excerpt": "The rain was coming down in sheets, pounding against my windshield. In that moment I realized — I wasn't just driving a car. I was driving through life itself.",
    "content": "<p>Today, I travelled to bring my daughter home for Easter break — and suddenly, the rains came pouring down.</p><p>The rain was coming down in sheets, pounding against my windshield like a relentless drumbeat. The skies turned a dark, foreboding grey, and the droplets pounded against the glass with a force that made the road ahead almost invisible.</p><p>The windshield wipers sprang to life, swishing back and forth with a soothing rhythm that seemed to calm my racing heart. As they cleared the rain, I felt a glimmer of hope. <em>Maybe, just maybe, I could manage through this darkness after all.</em></p><h2>We All Need Wipers</h2><p>But the wipers kept swishing, clearing a path for me to see the road ahead. And I realized that I had my own wipers too — my faith, my hope, my loved ones. They are the ones who help me clear away the tears, who give me a glimpse of light when all seems lost.</p>",
    "coverImage": "/assets/images/blogs/storm-wipers.jpg",
    "coverImageAlt": "Rain on a windshield with wipers clearing the view",
    "categorySlug": "resilience-and-growth",
    "pillar": null,
    "topics": ["hope and resilience"],
    "tags": ["hope", "resilience", "faith", "mental strength", "healing", "inspiration", "storms"],
    "type": "observant",
    "status": "published",
    "source": "human",
    "scheduledFor": null,
    "publishedAt": 1744963200000,
    "readingTime": 4,
    "actualReadingTime": null,
    "metaTitle": "Your Wipers — Finding Hope in Life's Storms | Pain2Purpose",
    "metaDescription": "A rainy drive became a powerful lesson. Sandra Opara reflects on the faith and inner strength that help us see clearly when life's storms hit hardest.",
    "focusKeyword": "finding hope in difficult times",
    "isFeatured": false,
    "isArchived": false
  },
  {
    "title": "What Healthy Love Actually Looks Like",
    "slug": "what-healthy-love-actually-looks-like",
    "excerpt": "Most of us learned about love from people who were doing their best with what they had. Which means some of us learned it wrong. Here is what love actually looks like — not the movie version.",
    "content": "<p>Most of us learned about love from people who were themselves doing their best with what they had. Let me describe what healthy love actually looks like.</p><h2>Safety</h2><p>In healthy love, you can be honest. You can disagree without it becoming a crisis. You can be imperfect without it threatening the relationship.</p><h2>Mutuality</h2><p>Both people contribute. Healthy love is not 70/30. Mutuality is the core.</p><h2>Space</h2><p>Healthy love does not require you to disappear. You keep your interests and friendships.</p><h2>Repair</h2><p>All relationships have conflict. What distinguishes healthy ones is the capacity for repair. The ability to come back and move forward.</p>",
    "coverImage": "",
    "coverImageAlt": "Two people laughing together at a table, genuine and easy",
    "categorySlug": "healing-and-recovery",
    "pillar": null,
    "topics": ["healthy relationships"],
    "tags": ["love", "relationships", "healthy relationship", "marriage", "boundaries", "mental health", "counselling"],
    "type": "pillar",
    "status": "published",
    "source": "human",
    "scheduledFor": null,
    "publishedAt": 1746864000000,
    "readingTime": 6,
    "actualReadingTime": null,
    "metaTitle": "What Healthy Love Actually Looks Like | Pain2Purpose",
    "metaDescription": "Most of us learned love from imperfect teachers. Sandra Opara describes what a genuinely healthy relationship actually looks and feels like — beyond the movie version.",
    "focusKeyword": "healthy relationship signs what love looks like",
    "isFeatured": false,
    "isArchived": false
  },
  {
    "title": "Healing Is Not Linear — And That's Okay",
    "slug": "healing-is-not-linear",
    "excerpt": "You had three good weeks. You thought you were better. Then something small happened and you were back on the bathroom floor. This is not failure. This is healing.",
    "content": "<p>Healing is not a straight line. It loops. It backtracks. It spirals.</p><h2>The Setback Is Not the Beginning</h2><p>When you have a difficult day after good days, you do not go back to zero. You go back to a version of the hard that is now different from the first time. You have tools. You have insight.</p><h2>What to Do When You Slide Back</h2><p>Contact your support. Do the basics — water, rest, movement. <a href='/services/individual-counselling'>We are here for the whole journey.</a></p>",
    "coverImage": "",
    "coverImageAlt": "A winding path through a forest — not straight, but going forward",
    "categorySlug": "healing-and-recovery",
    "pillar": null,
    "topics": ["healing process", "relapse in recovery"],
    "tags": ["healing", "recovery", "mental health", "setbacks", "therapy", "resilience", "hope"],
    "type": "insight",
    "status": "published",
    "source": "human",
    "scheduledFor": null,
    "publishedAt": 1749888000000,
    "readingTime": 5,
    "actualReadingTime": null,
    "metaTitle": "Healing Is Not Linear — And That's Okay | Pain2Purpose",
    "metaDescription": "You had good weeks, then fell back. That is not failure — that is healing. Sandra Opara explains the non-linear nature of recovery and how to keep going.",
    "focusKeyword": "healing is not linear recovery setbacks",
    "isFeatured": false,
    "isArchived": false
  },
  {
    "title": "The Strength in Saying I Don't Know",
    "slug": "the-strength-in-saying-i-dont-know",
    "excerpt": "In Nigerian culture, not having an answer can feel shameful. Uncertainty is treated as weakness. But I have found that the people who say 'I don't know' clearly are often the wisest ones in the room.",
    "content": "<p>Uncertainty is not a flaw. Not knowing is the honest response to most of life's significant questions.</p><h2>The Truly Courageous Thing</h2><p>The courageous thing is to sit with the not-knowing. The clients who make the most profound breakthroughs are the ones who can say: <em>\"I don't know where to start.\"</em> That honesty is the beginning of everything.</p><p><a href='/services/individual-counselling'>Bring your questions here.</a></p>",
    "coverImage": "",
    "coverImageAlt": "A person sitting thoughtfully with an open notebook and pen",
    "categorySlug": "resilience-and-growth",
    "pillar": null,
    "topics": ["uncertainty", "self awareness"],
    "tags": ["uncertainty", "self awareness", "mental health", "personal growth", "Nigeria", "counselling", "wisdom"],
    "type": "micro",
    "status": "published",
    "source": "human",
    "scheduledFor": null,
    "publishedAt": 1752912000000,
    "readingTime": 4,
    "actualReadingTime": null,
    "metaTitle": "The Strength in Saying I Don't Know | Pain2Purpose",
    "metaDescription": "In Nigerian culture, uncertainty is treated as weakness. Sandra Opara argues that saying 'I don't know' is often the wisest — and bravest — thing you can do.",
    "focusKeyword": "uncertainty mental health personal growth Nigeria",
    "isFeatured": false,
    "isArchived": false
  },
  {
    "title": "Before You Write That Divorce Letter — Read This",
    "slug": "before-you-write-that-divorce-letter",
    "excerpt": "I am not here to tell you to stay. I am not here to tell you to go. I am here to tell you to be honest — with yourself, before you do anything else.",
    "content": "<p>I am not here to tell you to stay or go. Divorce is a serious decision that belongs entirely to you. What I am here to say is: be honest. With yourself.</p><h2>Questions Worth Sitting With</h2><p>Have both of you genuinely tried — with professional help? Is what you are running from the marriage — or a version of yourself that exists within it? Is the pain of leaving truly less than the pain of staying?</p><h2>There Is No Shame in Either Choice</h2><p>The shame is only in making the decision without honesty.</p>",
    "coverImage": "",
    "coverImageAlt": "Wedding rings on a table near an unsigned letter",
    "categorySlug": "sandras-journal",
    "pillar": null,
    "topics": ["divorce", "marriage decisions"],
    "tags": ["divorce", "marriage", "relationships", "counselling", "honesty", "Nigeria", "couples therapy"],
    "type": "insight",
    "status": "published",
    "source": "human",
    "scheduledFor": null,
    "publishedAt": 1755936000000,
    "readingTime": 5,
    "actualReadingTime": null,
    "metaTitle": "Before You Write That Divorce Letter — Read This | Pain2Purpose",
    "metaDescription": "Not to tell you to stay or go — but to urge honesty. Sandra Opara asks the hard questions every person should sit with before making an irreversible decision.",
    "focusKeyword": "divorce decision marriage counselling Nigeria",
    "isFeatured": false,
    "isArchived": false
  },
  {
    "title": "Living With Someone Who Has a Mental Illness",
    "slug": "living-with-someone-who-has-mental-illness",
    "excerpt": "You love them. You are also exhausted by them. And you feel guilty about the exhaustion, which makes you more exhausted. Nobody tells you what it's like to live beside the illness.",
    "content": "<p>Supporting someone with a mental illness is not a sacrifice that earns its value from your suffering. The most sustainable support is the kind that also accounts for the supporter.</p><h2>Your Needs Are Also Real</h2><p>You matter. Your limits are not a character flaw — they are a human reality. Supporting someone is exhausting. The guilt is the honest cost of loving someone through illness.</p><h2>What Helps</h2><p>Your own therapy. Space to say the truth of what it is like. <a href='/services/individual-counselling'>That is what this space is for.</a></p>",
    "coverImage": "",
    "coverImageAlt": "Two people side by side, one resting head on the other's shoulder, tired",
    "categorySlug": "healing-and-recovery",
    "pillar": null,
    "topics": ["family of mentally ill", "secondary trauma"],
    "tags": ["mental illness", "family support", "caregiving", "burnout", "relationships", "therapy", "healing"],
    "type": "cluster",
    "status": "published",
    "source": "human",
    "scheduledFor": null,
    "publishedAt": 1759564800000,
    "readingTime": 5,
    "actualReadingTime": null,
    "metaTitle": "Living With Someone Who Has a Mental Illness | Pain2Purpose",
    "metaDescription": "You love them. You're also exhausted by them. Sandra Opara speaks honestly to those who live and love beside mental illness — and reminds them they matter too.",
    "focusKeyword": "supporting mentally ill family member caregiver",
    "isFeatured": false,
    "isArchived": false
  },
  {
    "title": "When You've Outgrown the Friendship",
    "slug": "when-you-have-outgrown-the-friendship",
    "excerpt": "You've changed. You've grown. You no longer have the same things to talk about. And the friendship that once felt like home now feels like a room you've grown too big for. This is allowed.",
    "content": "<p>Friendships have seasons. You are not a bad person for needing different things than you needed five years ago. Growth always changes the dynamics of relationships.</p><h2>Signs That a Friendship Has Run Its Course</h2><p>You consistently feel worse after spending time with them. You have stopped being honest because you know how they'll respond.</p><h2>How to Navigate It</h2><p>Most friendship endings don't require a dramatic conversation. They are best navigated with kindness and honesty. Growing is not betrayal.</p>",
    "coverImage": "",
    "coverImageAlt": "Two people walking apart on a path, moving in different directions",
    "categorySlug": "resilience-and-growth",
    "pillar": null,
    "topics": ["friendship endings", "personal growth"],
    "tags": ["friendship", "personal growth", "relationships", "boundaries", "change", "mental health", "self awareness"],
    "type": "observant",
    "status": "published",
    "source": "human",
    "scheduledFor": null,
    "publishedAt": 1763193600000,
    "readingTime": 5,
    "actualReadingTime": null,
    "metaTitle": "When You've Outgrown the Friendship | Pain2Purpose",
    "metaDescription": "Growing apart from a friend doesn't make you a bad person — it makes you human. Sandra Opara talks about the quiet, guilt-laden experience of outgrowing a friendship.",
    "focusKeyword": "outgrowing friendship relationships personal growth",
    "isFeatured": false,
    "isArchived": false
  },
  {
    "title": "A New Year Does Not Fix an Old Wound",
    "slug": "a-new-year-does-not-fix-an-old-wound",
    "excerpt": "January 1st is a date, not a cure. The pain you carried into this year did not vanish at midnight. But this is the year you can choose to actually do something about it.",
    "content": "<p>January 1st is a date on the calendar. It is not a cure. Whatever you carried into this year came with you. It always does.</p><h2>What Actually Helps</h2><p>Decision followed by action. Healing is not a feeling that arrives uninvited. It is a direction you choose.</p><h2>This Can Be the Year</h2><p>Not because of the date. Because you decide it is. Because you stop waiting for the pain to dissolve on its own. <a href='/services/individual-counselling'>We are here.</a></p>",
    "coverImage": "",
    "coverImageAlt": "A person writing in a journal on New Year's Day, candle lit beside them",
    "categorySlug": "sandras-journal",
    "pillar": null,
    "topics": ["new year mental health", "intention setting"],
    "tags": ["new year", "healing", "mental health", "intention", "therapy", "resilience", "Nigeria"],
    "type": "micro",
    "status": "published",
    "source": "human",
    "scheduledFor": null,
    "publishedAt": 1767427200000,
    "readingTime": 4,
    "actualReadingTime": null,
    "metaTitle": "A New Year Does Not Fix an Old Wound | Pain2Purpose",
    "metaDescription": "January 1st is a date, not a cure. Sandra Opara speaks honestly about what new year expectations do to people carrying real pain — and what actually helps.",
    "focusKeyword": "new year mental health healing intention",
    "isFeatured": false,
    "isArchived": false
  },
  {
    "title": "Why I Believe in Human Beings",
    "slug": "why-i-believe-in-human-beings",
    "excerpt": "After years of sitting with people in their darkest rooms, I have never once lost my belief in the resilience of the human spirit. This is my reminder — to you and to me.",
    "content": "<p>I have sat with people in their darkest rooms. And in every room, I have watched something happen that I believe is remarkable: people heal.</p><h2>What I Know After Years of This Work</h2><p>I know that the capacity for resilience is in ordinary people. Seeking help is not weakness. It is the earliest expression of resilience.</p><h2>This Is For You</h2><p>Wherever you are in your story, I believe in you. Your next chapter has not been written yet. <a href='/services/individual-counselling'>Come and write it. We are here.</a></p>",
    "coverImage": "",
    "coverImageAlt": "Sunrise over a quiet landscape, warm and full of light",
    "categorySlug": "sandras-journal",
    "pillar": null,
    "topics": ["hope", "human resilience"],
    "tags": ["hope", "resilience", "healing", "mental health", "counselling", "Sandra", "inspiration"],
    "type": "micro",
    "status": "published",
    "source": "human",
    "scheduledFor": null,
    "publishedAt": 1772697600000,
    "readingTime": 4,
    "actualReadingTime": null,
    "metaTitle": "Why I Believe in Human Beings | Pain2Purpose",
    "metaDescription": "After years of sitting with people in their darkest rooms, Sandra Opara has never lost her belief in the resilience of the human spirit. This is her reminder to you.",
    "focusKeyword": "human resilience hope healing counselling",
    "isFeatured": true,
    "isArchived": false
  }
];
